framework:
  secret: '%env(APP_SECRET)%'
  handle_all_throwables: true
  http_method_override: false
  php_errors:
    log: true
  messenger:
    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%'
    routing:
      App\Application\Decision\Message\VoteCastEvent: async
      App\Application\Decision\Message\RecomputeSessionResult: async

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
