services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'

  App\Application\Decision\ResultUpdatedPublisher:
    alias: App\Infrastructure\Mercure\NoOpResultUpdatedPublisher
