services:
  App\Tests\Infrastructure\Mercure\RecordingResultUpdatedPublisher:
    public: true

  App\Application\Decision\ResultUpdatedPublisher:
    alias: App\Tests\Infrastructure\Mercure\RecordingResultUpdatedPublisher
    public: true
